services:

  froom-api:
    build:
      context: froom
    labels:
      - "traefik.http.routers.froom-api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.froom-api.loadbalancer.sticky=true"
      - "traefik.http.services.froom-api.loadbalancer.sticky.cookie.name=StickyCookie"
      - "traefik.http.services.froom-api.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.routers.froom-api.tls=true"
      - "traefik.http.routers.froom-api.entrypoints=websecure"
      - io.portainer.accesscontrol.public
    deploy:
      replicas: 5

  froom-static:
    build: 
      context: froom-static
    labels:
      - "traefik.http.routers.froom-static.rule=Host(`localhost`)"
      - "traefik.http.routers.froom-static.tls=true"
      - "traefik.http.routers.froom-static.entrypoints=websecure"
      - io.portainer.accesscontrol.public
    deploy:
      replicas: 5

  traefik:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/etc/traefik/certificates
      - ./traefik.yaml:/etc/traefik/traefik.yaml

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
