services:
  froom-static:
    build: 
      context: froom-static
    labels:
      - "traefik.http.routers.froom-static.rule=Host(`localhost`) && !PathPrefix(`/api`)"

  froom-api:
    build:
      context: froom
    labels:
    - "traefik.http.routers.froom-api.rule=Host(`localhost`) && PathPrefix(`/api`)"

  traefik:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
